name: Deploy Bluesky Gold Bot

on:
  push:
    branches:
      - main  # یا branch دیگری که کد را در آن می‌خواهید اجرا کنید

jobs:
  deploy:
    runs-on: ubuntu-latest  # سیستم‌عامل که می‌خواهید روی آن اجرا شود

    steps:
    - name: Check out repository
      uses: actions/checkout@v2  # چک کردن کد ریپازیتوری

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # نسخه‌ای که می‌خواهید استفاده کنید

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # نصب وابستگی‌های پروژه

    - name: Run the bot
      run: |
        nohup python bot.py &  # اجرای سرور Flask در پس‌زمینه
